[[commands]]
name = "Xinit"
command = "startx"

[[commands]]
name = "echo"
command = "echo"
args = ["Hi", "mom", "!"]

[[commands]]
name = "Print working directory"
command = "pwd"

[[commands]]
name = "Nothing"

[[commands]]
name = "fail"
command = "false"

[[commands]]
name = "fail with output"
command = "cat"
args = ["--does-not-exist"]
